function [table_to_show] = calcSvmLossTnV(  c_data_for_classifier, vClass,...
                                            description_for_data, all_base_functions,...
                                            table_to_show )
    
    for ii = 1 : length(c_data_for_classifier)
    
        %-- SVM Kernal
        for base_func = all_base_functions
            tmp =  showSvmResultsAllTraining( c_data_for_classifier{ii},...
                                              vClass,...
                                              description_for_data(ii),...
                                              base_func );
            table_to_show = [ table_to_show;
                              showSvmResults( c_data_for_classifier{ii},...
                                              vClass,...
                                              description_for_data(ii),...
                                              base_func ) ,tmp(3)...
                                              ];

%                 table_to_show = [ table_to_show; 
%                                   showSvmResultsNoDiag( v_classifier,...
%                                                         vClass,...
%                                                         description_of_classifier_and_fetures,...
%                                                         base_func,...
%                                                         size(vectors_of_features,1)) ];
        end
    end
end

